name: Pest 
 
on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 
 
jobs: 
  test: 
    runs-on: ubuntu-latest 
 
    steps: 
    - uses: actions/checkout@v3 
 
    - name: Set up PHP 
      uses: shivammathur/setup-php@v2 
      with: 
        php-version: '8.4' 
        extensions: mbstring, pdo, json, bcmath, ctype 
 
    - name: Clear Composer Cache 
      run: composer clear-cache 
 
    - name: Install Dependencies 
      run: composer install --prefer-dist --no-interaction --optimize-autoloader 
 
    - name: Run Tests 
      run: vendor/bin/pest